2019-11-16 16:07:33,515 : kivy : Factory: 184 symbols loaded
2019-11-16 16:07:33,606 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-11-16 16:07:33,654 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2019-11-16 16:07:33,654 : kivy : Video: Provider: gstplayer
2019-11-16 16:07:33,717 : kivy : Loading MPF-MC controller
2019-11-16 16:07:33,717 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.15
2019-11-16 16:07:33,717 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.68
2019-11-16 16:07:33,718 : mpfmc : Machine path: D:\mpf\wows\wows
2019-11-16 16:07:33,718 : ConfigProcessor : Config file in cache changed: D:\mpf\wows\wows\config\config
2019-11-16 16:07:33,719 : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2019-11-16 16:07:33,763 : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2019-11-16 16:07:33,769 : ConfigProcessor : Loading config from file D:\mpf\wows\wows\config\config.
2019-11-16 16:07:33,822 : kivy : Error found in file D:\mpf\wows\wows\config\config.yaml: 'Key "target" was defined multiple times in config   in "D:\\mpf\\wows\\wows\\config\\config.yaml", line 322, column 3'
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "target" was defined multiple times in config   in "D:\\mpf\\wows\\wows\\config\\config.yaml", line 322, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 211, in load
    raise ValueError(msg)
ValueError: Error found in file D:\mpf\wows\wows\config\config.yaml: 'Key "target" was defined multiple times in config   in "D:\\mpf\\wows\\wows\\config\\config.yaml", line 322, column 3'
2019-11-16 16:07:33,824 : kivy : Stopping child threads... (0 remaining)
2019-11-16 16:07:33,824 : kivy : All child threads stopped.
