2019-11-16 15:09:24,371 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.68
2019-11-16 15:09:24,372 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-11-16-15-09-24-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-11-16 15:09:24,372 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-11-16 15:09:24,372 : INFO : Machine : Machine path: D:\mpf\wows\wows
2019-11-16 15:09:24,372 : INFO : Machine : Platform: win32
2019-11-16 15:09:24,372 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2019-11-16 15:09:24,372 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-11-16 15:09:24,372 : INFO : Machine : Machine config file #1: config.yaml
2019-11-16 15:09:24,373 : WARNING : ConfigProcessor : Config file in cache changed: D:\mpf\wows\wows\config\config.yaml
2019-11-16 15:09:24,373 : INFO : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-11-16 15:09:24,450 : INFO : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-11-16 15:09:24,457 : INFO : ConfigProcessor : Loading config from file D:\mpf\wows\wows\config\config.yaml.
2019-11-16 15:09:24,510 : INFO : ConfigProcessor : Loading config: D:\mpf\wows\wows\config\config.yaml
2019-11-16 15:09:24,512 : INFO : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\9eb68d3894805241b8cf789ebd176e3c.mpf_cache
2019-11-16 15:09:24,513 : INFO : Machine : Initialise MPF.
2019-11-16 15:09:24,777 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,817 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-11-16 15:09:24,817 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.68', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,817 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.68, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,817 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,818 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,818 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,818 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,818 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,818 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-11-16 15:09:24,818 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-11-16 15:09:24,848 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2019-11-16 15:09:24,852 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2019-11-16 15:09:24,857 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a8b20f4baab78a690a96d03fe506ff8d.mpf_cache
2019-11-16 15:09:24,872 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ot defined',)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:90
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ot defined',)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:90>
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 93, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 113, in _load_device_modules
    self.load_devices_config(validate=True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 177, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device.py", line 103, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 281, in validate_config
    validation_failure_info=(validation_failure_info, k))
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 320, in validate_config_item
    validation_failure_info)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 757, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 477, in _validate_type_machine
    6)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 776, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_devices:bd_plunger:eject_coil = "c_plunger_eject" is not valid. Device c_plunger_eject of type coils not defined Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-6.html)
2019-11-16 15:09:24,874 : INFO : Machine : Starting the main run loop.
2019-11-16 15:09:24,877 : INFO : Machine : Shutting down...
2019-11-16 15:09:24,877 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-11-16 15:09:24,878 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 93, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 113, in _load_device_modules
    self.load_devices_config(validate=True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device_manager.py", line 177, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\device.py", line 103, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 281, in validate_config
    validation_failure_info=(validation_failure_info, k))
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 320, in validate_config_item
    validation_failure_info)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 757, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 477, in _validate_type_machine
    6)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_validator.py", line 776, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_devices:bd_plunger:eject_coil = "c_plunger_eject" is not valid. Device c_plunger_eject of type coils not defined Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/dev/logs/CFE-ConfigValidator-6.html)
2019-11-16 15:09:24,879 : INFO : root : MPF run loop ended.
