2019-12-20 18:37:17,201 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.68
2019-12-20 18:37:17,201 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-12-20-18-37-17-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-12-20 18:37:17,201 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-12-20 18:37:17,201 : INFO : Machine : Machine path: D:\mpf\wows\wows
2019-12-20 18:37:17,201 : INFO : Machine : Platform: win32
2019-12-20 18:37:17,201 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2019-12-20 18:37:17,201 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-12-20 18:37:17,201 : INFO : Machine : Machine config file #1: config.yaml
2019-12-20 18:37:17,202 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\9eb68d3894805241b8cf789ebd176e3c.mpf_cache
2019-12-20 18:37:17,204 : INFO : Machine : Initialise MPF.
2019-12-20 18:37:17,417 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,455 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-12-20 18:37:17,455 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.68', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,455 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.68, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,455 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,456 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,456 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,456 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,456 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,456 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-12-20 18:37:17,456 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-12-20 18:37:17,486 : WARNING : ConfigProcessor : Config file in cache changed: D:\mpf\wows\wows\modes\mode_lit\config\mode_lit.yaml
2019-12-20 18:37:17,486 : INFO : ConfigProcessor : Loading config from file D:\mpf\wows\wows\modes\mode_lit\config\mode_lit.yaml.
2019-12-20 18:37:17,506 : INFO : ConfigProcessor : Loading config: D:\mpf\wows\wows\modes\mode_lit\config\mode_lit.yaml
2019-12-20 18:37:17,507 : INFO : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\bb4559fa659cc8b2de1dccf407dfe109.mpf_cache
2019-12-20 18:37:17,509 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2019-12-20 18:37:17,513 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2019-12-20 18:37:17,517 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\e8c0a02b20549d458f541dd443ff3ce4.mpf_cache
2019-12-20 18:37:17,519 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a327e3a062200f866ce963b9d13b0dd9.mpf_cache
2019-12-20 18:37:17,544 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2019-12-20 18:37:17,544 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>)
2019-12-20 18:37:17,545 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>)
2019-12-20 18:37:17,545 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>)
2019-12-20 18:37:17,545 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>)
2019-12-20 18:37:17,545 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>)
2019-12-20 18:37:17,545 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>)
2019-12-20 18:37:17,548 : ERROR : asyncio : Exception in callback EventManager._done(<Task finishe...ights None',)>)
handle: <Handle EventManager._done(<Task finishe...ights None',)>)>
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 695, in _done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 612, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 96, in initialise_modes
    mode.initialise_mode()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 576, in initialise_mode
    **item.kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 53, in _process_config_shows_section
    self.register_show(show, settings)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 66, in register_show
    file=None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 76, in __init__
    self._do_load_show(data=data)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 174, in _do_load_show
    self._process_step_actions(step, actions)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 204, in _process_step_actions
    actions[key] = self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\config_players\device_config_player.py", line 43, in validate_config_entry
    name, self.show_section, settings))
AssertionError: Invalid settings for player flash:lights None
2019-12-20 18:37:17,624 : INFO : Machine : Starting the main run loop.
2019-12-20 18:37:17,626 : INFO : Machine : Shutting down...
2019-12-20 18:37:17,627 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-12-20 18:37:17,627 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 695, in _done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 612, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 96, in initialise_modes
    mode.initialise_mode()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode.py", line 576, in initialise_mode
    **item.kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 53, in _process_config_shows_section
    self.register_show(show, settings)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\show_controller.py", line 66, in register_show
    file=None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 76, in __init__
    self._do_load_show(data=data)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 174, in _do_load_show
    self._process_step_actions(step, actions)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\assets\show.py", line 204, in _process_step_actions
    actions[key] = self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\config_players\device_config_player.py", line 43, in validate_config_entry
    name, self.show_section, settings))
AssertionError: Invalid settings for player flash:lights None
2019-12-20 18:37:17,638 : INFO : root : MPF run loop ended.
