2019-11-13 16:57:03,352 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.67
2019-11-13 16:57:03,352 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-11-13-16-57-03-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-11-13 16:57:03,352 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-11-13 16:57:03,352 : INFO : Machine : Machine path: D:\mpf\wows\wows
2019-11-13 16:57:03,352 : INFO : Machine : Platform: win32
2019-11-13 16:57:03,352 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2019-11-13 16:57:03,352 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-11-13 16:57:03,353 : INFO : Machine : Machine config file #1: config.yaml
2019-11-13 16:57:03,353 : WARNING : ConfigProcessor : Config file in cache changed: D:\mpf\wows\wows\config\config.yaml
2019-11-13 16:57:03,354 : INFO : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-11-13 16:57:03,430 : INFO : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-11-13 16:57:03,437 : INFO : ConfigProcessor : Loading config from file D:\mpf\wows\wows\config\config.yaml.
2019-11-13 16:57:03,445 : ERROR : root : YAML error found in file D:\mpf\wows\wows\config\config.yaml. Line 47, Position 7: while parsing a block collection
  in "D:\mpf\wows\wows\config\config.yaml", line 46, column 7
expected <block end>, but found '?'
  in "D:\mpf\wows\wows\config\config.yaml", line 47, column 7
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 130, in compose_node
    node = self.compose_sequence_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 162, in compose_sequence_node
    while not self.parser.check_event(SequenceEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 500, in parse_block_sequence_entry
    token.id, token.start_mark)
ruamel.yaml.parser.ParserError: while parsing a block collection
  in "D:\mpf\wows\wows\config\config.yaml", line 46, column 7
expected <block end>, but found '?'
  in "D:\mpf\wows\wows\config\config.yaml", line 47, column 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 226, in __init__
    self.machine = MachineController(mpf_path, machine_path, vars(self.args))
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 199, in __init__
    self._load_config()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 431, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file D:\mpf\wows\wows\config\config.yaml. Line 47, Position 7: while parsing a block collection
  in "D:\mpf\wows\wows\config\config.yaml", line 46, column 7
expected <block end>, but found '?'
  in "D:\mpf\wows\wows\config\config.yaml", line 47, column 7
