2020-02-04 22:23:05,182 : kivy : Factory: 184 symbols loaded
2020-02-04 22:23:05,278 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2020-02-04 22:23:05,329 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2020-02-04 22:23:05,329 : kivy : Video: Provider: gstplayer
2020-02-04 22:23:05,392 : kivy : Loading MPF-MC controller
2020-02-04 22:23:05,393 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.15
2020-02-04 22:23:05,393 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.68
2020-02-04 22:23:05,393 : mpfmc : Machine path: E:\mpf\wows\wows
2020-02-04 22:23:05,394 : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\config\config
2020-02-04 22:23:05,395 : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2020-02-04 22:23:05,440 : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2020-02-04 22:23:05,447 : ConfigProcessor : Loading config from file E:\mpf\wows\wows\config\config.
2020-02-04 22:23:05,534 : ConfigProcessor : Loading config: E:\mpf\wows\wows\config\config
2020-02-04 22:23:05,536 : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\398a03908486e3c8525902f452489fb5.mpf_cache
2020-02-04 22:23:05,537 : mpfmc : Starting clock at 60.0Hz
2020-02-04 22:23:05,548 : kivy : Text: Provider: sdl2
2020-02-04 22:23:05,583 : kivy : Window: Provider: sdl2
2020-02-04 22:23:05,971 : kivy : GL: Using the "OpenGL" graphics system
2020-02-04 22:23:05,977 : kivy : GL: GLEW initialization succeeded
2020-02-04 22:23:05,978 : kivy : GL: Backend used <glew>
2020-02-04 22:23:05,978 : kivy : GL: OpenGL version <b'4.6.0 NVIDIA 432.00'>
2020-02-04 22:23:05,978 : kivy : GL: OpenGL vendor <b'NVIDIA Corporation'>
2020-02-04 22:23:05,978 : kivy : GL: OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
2020-02-04 22:23:05,978 : kivy : GL: OpenGL parsed version: 4, 6
2020-02-04 22:23:05,978 : kivy : GL: Shading version <b'4.60 NVIDIA'>
2020-02-04 22:23:05,978 : kivy : GL: Texture max size <32768>
2020-02-04 22:23:05,978 : kivy : GL: Texture max units <32>
2020-02-04 22:23:05,996 : kivy : Window: auto add sdl2 input provider
2020-02-04 22:23:05,996 : kivy : Window: virtual keyboard not allowed, single mode, not docked
2020-02-04 22:23:06,004 : SoundSystem : SoundSystem: Using default 'sound_system' settings
2020-02-04 22:23:06,215 : AudioInterface : Initialized
2020-02-04 22:23:06,215 : SoundSystem : No audio tracks are specified in your machine config file. a track named 'default' has been created.
2020-02-04 22:23:06,217 : kivy : Base: Start application main loop
2020-02-04 22:23:06,217 : EventManager : Event: ======'display_window_initialized'====== Args={}
2020-02-04 22:23:06,217 : EventManager : Event: ======'display_dmd_initialized'====== Args={}
2020-02-04 22:23:06,277 : mpfmc : Display: Setting 'dmd' as default display
2020-02-04 22:23:06,283 : EventManager : Event: ======'displays_initialized'====== Args={}
2020-02-04 22:23:06,284 : EventManager : Event: ======'slide_window_blank_created'====== Args={}
2020-02-04 22:23:06,284 : EventManager : Event: ======'display_window_ready'====== Args={}
2020-02-04 22:23:06,285 : EventManager : Event: ======'slide_dmd_blank_created'====== Args={}
2020-02-04 22:23:06,285 : EventManager : Event: ======'display_dmd_ready'====== Args={}
2020-02-04 22:23:06,294 : EventManager : Event: ======'init_phase_1'====== Args={}
2020-02-04 22:23:06,297 : EventManager : Event: ======'mc_ready'====== Args={}
2020-02-04 22:23:06,297 : EventManager : Event: ======'init_phase_2'====== Args={}
2020-02-04 22:23:06,298 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2020-02-04 22:23:06,298 : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml
2020-02-04 22:23:06,298 : ConfigProcessor : Loading config from file E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml.
2020-02-04 22:23:06,306 : kivy : Base: Leaving application in progress...
2020-02-04 22:23:06,306 : kivy : Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x000002342F08BFD0>>, priority=1, kwargs={}, key=UUID('7aeafe2c-672a-4e38-a031-c8fe0c3bcd68'), condition=None, blocking_facility=None) for event init_phase_2
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 547, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 160, in check_token
    self.fetch_more_tokens()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 297, in fetch_more_tokens
    return self.fetch_single()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 694, in fetch_single
    self.fetch_flow_scalar(style='\'')
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 707, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 1276, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 1373, in scan_flow_scalar_spaces
    "found unexpected end of stream", self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
  in "E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml", line 40, column 1
found unexpected end of stream
  in "E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml", line 69, column 19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 662, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 59, in _load_modes
    self.mc.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 132, in _load_mode
    store_to_cache=self.mc.options['create_config_cache'], ignore_unknown_sections=True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml. Line 69, Position 19: while scanning a quoted scalar
  in "E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml", line 40, column 1
found unexpected end of stream
  in "E:\mpf\wows\wows\modes\hc_lock_lit\config\hc_lock_lit.yaml", line 69, column 19

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\clock.py", line 591, in tick
    self._process_events()
  File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\uix\display.py", line 205, in _displays_initialized
    self.mc.displays_initialized()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 336, in displays_initialized
    self._init()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 380, in _init
    self.events.process_event_queue()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 743, in process_event_queue
    **event[3])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 708, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 664, in _run_handlers
    raise Exception("Exception while processing {} for event {}".format(handler, event)) from e
Exception: Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x000002342F08BFD0>>, priority=1, kwargs={}, key=UUID('7aeafe2c-672a-4e38-a031-c8fe0c3bcd68'), condition=None, blocking_facility=None) for event init_phase_2
2020-02-04 22:23:06,381 : kivy : Stopping child threads... (1 remaining)
2020-02-04 22:23:07,285 : kivy : All child threads stopped.
