2020-04-08 18:06:00,333 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.2
2020-04-08 18:06:00,333 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-04-08-18-06-00-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-04-08 18:06:00,334 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2020-04-08 18:06:00,334 : INFO : Machine : Machine path: E:\MPF\wows\wows
2020-04-08 18:06:00,334 : INFO : Machine : Platform: win32
2020-04-08 18:06:00,334 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2020-04-08 18:06:00,334 : INFO : Machine : Python version: 3.6.4 (64-bit)
2020-04-08 18:06:00,334 : INFO : Machine : Machine config file #1: config.yaml
2020-04-08 18:06:00,335 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1ed54315bc874a19390ba34e1a0f1800.mpf_cache
2020-04-08 18:06:00,337 : INFO : Machine : Initialise MPF.
2020-04-08 18:06:00,783 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,822 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2020-04-08 18:06:00,822 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.2', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,822 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.2, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,822 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,822 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,822 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,823 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,823 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,823 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2020-04-08 18:06:00,823 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-04-08 18:06:00,857 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\0c80ca2179989d09b86c78c19ec87d9b.mpf_cache
2020-04-08 18:06:00,859 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\200a9b2dddbe7706ffb4c4426b6d54a8.mpf_cache
2020-04-08 18:06:00,861 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\159a0b7ffc6de2ed1a8cdcd57b7df3c0.mpf_cache
2020-04-08 18:06:00,863 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\95ae88fb094583fa2b4097c6df179650.mpf_cache
2020-04-08 18:06:00,865 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\4303dca7489148da2d256fc831cf8c96.mpf_cache
2020-04-08 18:06:00,867 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\2f89b2ab1d9f3cef79a660914b2a527a.mpf_cache
2020-04-08 18:06:00,869 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\b1234e2c44a33609dc2af4760c4a3f89.mpf_cache
2020-04-08 18:06:00,871 : WARNING : ConfigProcessor : Config file in cache changed: E:\MPF\wows\wows\modes\port_hole_manager\config\port_hole_manager.yaml
2020-04-08 18:06:00,871 : INFO : ConfigProcessor : Loading config from file E:\MPF\wows\wows\modes\port_hole_manager\config\port_hole_manager.yaml.
2020-04-08 18:06:00,877 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:99
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 3\'',)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:99>
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 218, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 111, in get_single_data
    return self.construct_document(node)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 121, in construct_document
    for _dummy in generator:
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 713, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "port_check_phase_3_started" was defined multiple times in config   in "E:\\MPF\\wows\\wows\\modes\\port_hole_manager\\config\\port_hole_manager.yaml", line 41, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 102, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 110, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 259, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 177, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 207, in load
    raise ValueError(msg)
ValueError: Error found in file E:\MPF\wows\wows\modes\port_hole_manager\config\port_hole_manager.yaml: 'Key "port_check_phase_3_started" was defined multiple times in config   in "E:\\MPF\\wows\\wows\\modes\\port_hole_manager\\config\\port_hole_manager.yaml", line 41, column 3'
2020-04-08 18:06:00,947 : INFO : Machine : Starting the main run loop.
2020-04-08 18:06:00,952 : INFO : Machine : Shutting down...
2020-04-08 18:06:00,952 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-04-08 18:06:00,953 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 218, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 111, in get_single_data
    return self.construct_document(node)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 121, in construct_document
    for _dummy in generator:
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 713, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "port_check_phase_3_started" was defined multiple times in config   in "E:\\MPF\\wows\\wows\\modes\\port_hole_manager\\config\\port_hole_manager.yaml", line 41, column 3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 102, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 110, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 259, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 177, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 207, in load
    raise ValueError(msg)
ValueError: Error found in file E:\MPF\wows\wows\modes\port_hole_manager\config\port_hole_manager.yaml: 'Key "port_check_phase_3_started" was defined multiple times in config   in "E:\\MPF\\wows\\wows\\modes\\port_hole_manager\\config\\port_hole_manager.yaml", line 41, column 3'
2020-04-08 18:06:00,964 : INFO : root : MPF run loop ended.
