2020-01-25 12:14:41,708 : kivy : Factory: 184 symbols loaded
2020-01-25 12:14:41,802 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2020-01-25 12:14:41,851 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2020-01-25 12:14:41,851 : kivy : Video: Provider: gstplayer
2020-01-25 12:14:41,913 : kivy : Loading MPF-MC controller
2020-01-25 12:14:41,914 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.15
2020-01-25 12:14:41,914 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.68
2020-01-25 12:14:41,914 : mpfmc : Machine path: E:\mpf\wows\wows
2020-01-25 12:14:41,915 : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\config\config
2020-01-25 12:14:41,916 : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2020-01-25 12:14:41,959 : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2020-01-25 12:14:41,966 : ConfigProcessor : Loading config from file E:\mpf\wows\wows\config\config.
2020-01-25 12:14:42,051 : ConfigProcessor : Loading config: E:\mpf\wows\wows\config\config
2020-01-25 12:14:42,052 : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\398a03908486e3c8525902f452489fb5.mpf_cache
2020-01-25 12:14:42,053 : mpfmc : Starting clock at 60.0Hz
2020-01-25 12:14:42,064 : kivy : Text: Provider: sdl2
2020-01-25 12:14:42,100 : kivy : Window: Provider: sdl2
2020-01-25 12:14:42,543 : kivy : GL: Using the "OpenGL" graphics system
2020-01-25 12:14:42,549 : kivy : GL: GLEW initialization succeeded
2020-01-25 12:14:42,550 : kivy : GL: Backend used <glew>
2020-01-25 12:14:42,550 : kivy : GL: OpenGL version <b'4.6.0 NVIDIA 432.00'>
2020-01-25 12:14:42,550 : kivy : GL: OpenGL vendor <b'NVIDIA Corporation'>
2020-01-25 12:14:42,550 : kivy : GL: OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
2020-01-25 12:14:42,550 : kivy : GL: OpenGL parsed version: 4, 6
2020-01-25 12:14:42,550 : kivy : GL: Shading version <b'4.60 NVIDIA'>
2020-01-25 12:14:42,550 : kivy : GL: Texture max size <32768>
2020-01-25 12:14:42,550 : kivy : GL: Texture max units <32>
2020-01-25 12:14:42,567 : kivy : Window: auto add sdl2 input provider
2020-01-25 12:14:42,567 : kivy : Window: virtual keyboard not allowed, single mode, not docked
2020-01-25 12:14:42,574 : SoundSystem : SoundSystem: Using default 'sound_system' settings
2020-01-25 12:14:42,783 : AudioInterface : Initialized
2020-01-25 12:14:42,783 : SoundSystem : No audio tracks are specified in your machine config file. a track named 'default' has been created.
2020-01-25 12:14:42,785 : kivy : Base: Start application main loop
2020-01-25 12:14:42,786 : EventManager : Event: ======'display_window_initialized'====== Args={}
2020-01-25 12:14:42,786 : EventManager : Event: ======'display_dmd_initialized'====== Args={}
2020-01-25 12:14:42,845 : mpfmc : Display: Setting 'dmd' as default display
2020-01-25 12:14:42,851 : EventManager : Event: ======'displays_initialized'====== Args={}
2020-01-25 12:14:42,852 : EventManager : Event: ======'slide_window_blank_created'====== Args={}
2020-01-25 12:14:42,852 : EventManager : Event: ======'display_window_ready'====== Args={}
2020-01-25 12:14:42,853 : EventManager : Event: ======'slide_dmd_blank_created'====== Args={}
2020-01-25 12:14:42,853 : EventManager : Event: ======'display_dmd_ready'====== Args={}
2020-01-25 12:14:42,861 : EventManager : Event: ======'init_phase_1'====== Args={}
2020-01-25 12:14:42,865 : EventManager : Event: ======'mc_ready'====== Args={}
2020-01-25 12:14:42,865 : EventManager : Event: ======'init_phase_2'====== Args={}
2020-01-25 12:14:42,866 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\6e6d4708a613edd7635d35a6961997f3.mpf_cache
2020-01-25 12:14:42,867 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\4aeaa69609f53d9b71d1dbbedd434b0b.mpf_cache
2020-01-25 12:14:42,867 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2020-01-25 12:14:42,867 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1e6cc6775e87a3e14ded8d45fd065b10.mpf_cache
2020-01-25 12:14:42,868 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2020-01-25 12:14:42,869 : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1068177614fe5a40fc2c1e1b0504468c.mpf_cache
2020-01-25 12:14:42,869 : ConfigProcessor : Cache file not found: C:\Users\schol\AppData\Local\Temp\a6527a592b6034dbfea56fdf726c3822.mpf_cache
2020-01-25 12:14:42,869 : ConfigProcessor : Loading config from file E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml.
2020-01-25 12:14:42,874 : kivy : Base: Leaving application in progress...
2020-01-25 12:14:42,875 : kivy : Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x00000228D374CF60>>, priority=1, kwargs={}, key=UUID('b6b1d2a5-93c9-4b80-830b-a1ec1e2061a8'), condition=None, blocking_facility=None) for event init_phase_2
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 547, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 160, in check_token
    self.fetch_more_tokens()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 273, in fetch_more_tokens
    return self.fetch_value()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 626, in fetch_value
    self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 662, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 59, in _load_modes
    self.mc.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 132, in _load_mode
    store_to_cache=self.mc.options['create_config_cache'], ignore_unknown_sections=True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml. Line 34, Position 35: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\clock.py", line 591, in tick
    self._process_events()
  File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\uix\display.py", line 205, in _displays_initialized
    self.mc.displays_initialized()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 336, in displays_initialized
    self._init()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 380, in _init
    self.events.process_event_queue()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 743, in process_event_queue
    **event[3])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 708, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 664, in _run_handlers
    raise Exception("Exception while processing {} for event {}".format(handler, event)) from e
Exception: Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x00000228D374CF60>>, priority=1, kwargs={}, key=UUID('b6b1d2a5-93c9-4b80-830b-a1ec1e2061a8'), condition=None, blocking_facility=None) for event init_phase_2
2020-01-25 12:14:42,880 : kivy : Stopping child threads... (1 remaining)
2020-01-25 12:14:43,786 : kivy : All child threads stopped.
