2020-01-25 12:12:18,993 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.68
2020-01-25 12:12:18,993 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\schol\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2020-01-25-12-12-18-mpf-DESKTOP-FPTMTCL.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2020-01-25 12:12:18,993 : INFO : Machine : MPF path: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf
2020-01-25 12:12:18,993 : INFO : Machine : Machine path: E:\mpf\wows\wows
2020-01-25 12:12:18,993 : INFO : Machine : Platform: win32
2020-01-25 12:12:18,993 : INFO : Machine : Python executable location: c:\users\schol\appdata\local\programs\python\python36\python.exe
2020-01-25 12:12:18,993 : INFO : Machine : Python version: 3.6.4 (64-bit)
2020-01-25 12:12:18,993 : INFO : Machine : Machine config file #1: config.yaml
2020-01-25 12:12:18,994 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\a7e9e9e882fa7eca7cb0ba00eaf15121.mpf_cache
2020-01-25 12:12:19,001 : INFO : Machine : Initialise MPF.
2020-01-25 12:12:19,229 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.68', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.68, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.18362-SP0', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.18362', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2020-01-25 12:12:19,265 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2020-01-25 12:12:19,297 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1068177614fe5a40fc2c1e1b0504468c.mpf_cache
2020-01-25 12:12:19,299 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\4aeaa69609f53d9b71d1dbbedd434b0b.mpf_cache
2020-01-25 12:12:19,301 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\5c4497fcd69d1d656c4b69a28e44c490.mpf_cache
2020-01-25 12:12:19,307 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\d5fd805c5432c1441bf01a6268536a3d.mpf_cache
2020-01-25 12:12:19,311 : INFO : ConfigProcessor : Loading config from cache: C:\Users\schol\AppData\Local\Temp\1e6cc6775e87a3e14ded8d45fd065b10.mpf_cache
2020-01-25 12:12:19,313 : WARNING : ConfigProcessor : Cache file not found: C:\Users\schol\AppData\Local\Temp\a6527a592b6034dbfea56fdf726c3822.mpf_cache
2020-01-25 12:12:19,313 : INFO : ConfigProcessor : Loading config from file E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml.
2020-01-25 12:12:19,319 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe... column 35',)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:90
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe... column 35',)>) at c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:90>
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 547, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 160, in check_token
    self.fetch_more_tokens()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 273, in fetch_more_tokens
    return self.fetch_value()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 626, in fetch_value
    self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 93, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 110, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 259, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 177, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml. Line 34, Position 35: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35
2020-01-25 12:12:19,323 : INFO : Machine : Starting the main run loop.
2020-01-25 12:12:19,325 : INFO : Machine : Shutting down...
2020-01-25 12:12:19,325 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2020-01-25 12:12:19,326 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 547, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 160, in check_token
    self.fetch_more_tokens()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 273, in fetch_more_tokens
    return self.fetch_value()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 626, in fetch_value
    self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 765, in _run_loop
    raise self._exception['exception']
  File "c:\users\schol\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 93, in _async_handler_done
    future.result()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 110, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 259, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 177, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml. Line 34, Position 35: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35
2020-01-25 12:12:19,328 : INFO : root : MPF run loop ended.
