2020-01-25 12:12:19,229 : kivy : Factory: 184 symbols loaded
2020-01-25 12:12:19,324 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2020-01-25 12:12:19,374 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2020-01-25 12:12:19,374 : kivy : Video: Provider: gstplayer
2020-01-25 12:12:19,438 : kivy : Loading MPF-MC controller
2020-01-25 12:12:19,438 : mpfmc : Mission Pinball Framework Media Controller v0.53.0-dev.15
2020-01-25 12:12:19,438 : mpfmc : Mission Pinball Framework Game Engine v0.53.0-dev.68
2020-01-25 12:12:19,438 : mpfmc : Machine path: E:\mpf\wows\wows
2020-01-25 12:12:19,439 : ConfigProcessor : Config file in cache changed: E:\mpf\wows\wows\config\config
2020-01-25 12:12:19,440 : ConfigProcessor : Loading config from file c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2020-01-25 12:12:19,484 : ConfigProcessor : Loading config: c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2020-01-25 12:12:19,491 : ConfigProcessor : Loading config from file E:\mpf\wows\wows\config\config.
2020-01-25 12:12:19,574 : ConfigProcessor : Loading config: E:\mpf\wows\wows\config\config
2020-01-25 12:12:19,576 : ConfigProcessor : Config file cache created: C:\Users\schol\AppData\Local\Temp\398a03908486e3c8525902f452489fb5.mpf_cache
2020-01-25 12:12:19,576 : mpfmc : Starting clock at 60.0Hz
2020-01-25 12:12:19,588 : kivy : Text: Provider: sdl2
2020-01-25 12:12:19,624 : kivy : Window: Provider: sdl2
2020-01-25 12:12:20,040 : kivy : GL: Using the "OpenGL" graphics system
2020-01-25 12:12:20,046 : kivy : GL: GLEW initialization succeeded
2020-01-25 12:12:20,047 : kivy : GL: Backend used <glew>
2020-01-25 12:12:20,047 : kivy : GL: OpenGL version <b'4.6.0 NVIDIA 432.00'>
2020-01-25 12:12:20,047 : kivy : GL: OpenGL vendor <b'NVIDIA Corporation'>
2020-01-25 12:12:20,047 : kivy : GL: OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
2020-01-25 12:12:20,047 : kivy : GL: OpenGL parsed version: 4, 6
2020-01-25 12:12:20,047 : kivy : GL: Shading version <b'4.60 NVIDIA'>
2020-01-25 12:12:20,047 : kivy : GL: Texture max size <32768>
2020-01-25 12:12:20,047 : kivy : GL: Texture max units <32>
2020-01-25 12:12:20,064 : kivy : Window: auto add sdl2 input provider
2020-01-25 12:12:20,064 : kivy : Window: virtual keyboard not allowed, single mode, not docked
2020-01-25 12:12:20,071 : SoundSystem : SoundSystem: Using default 'sound_system' settings
2020-01-25 12:12:20,280 : AudioInterface : Initialized
2020-01-25 12:12:20,280 : SoundSystem : No audio tracks are specified in your machine config file. a track named 'default' has been created.
2020-01-25 12:12:20,282 : kivy : Base: Start application main loop
2020-01-25 12:12:20,283 : EventManager : Event: ======'display_window_initialized'====== Args={}
2020-01-25 12:12:20,283 : EventManager : Event: ======'display_dmd_initialized'====== Args={}
2020-01-25 12:12:20,339 : mpfmc : Display: Setting 'dmd' as default display
2020-01-25 12:12:20,346 : EventManager : Event: ======'displays_initialized'====== Args={}
2020-01-25 12:12:20,347 : EventManager : Event: ======'slide_window_blank_created'====== Args={}
2020-01-25 12:12:20,347 : EventManager : Event: ======'display_window_ready'====== Args={}
2020-01-25 12:12:20,347 : EventManager : Event: ======'slide_dmd_blank_created'====== Args={}
2020-01-25 12:12:20,347 : EventManager : Event: ======'display_dmd_ready'====== Args={}
2020-01-25 12:12:20,356 : EventManager : Event: ======'init_phase_1'====== Args={}
2020-01-25 12:12:20,359 : EventManager : Event: ======'mc_ready'====== Args={}
2020-01-25 12:12:20,359 : EventManager : Event: ======'init_phase_2'====== Args={}
2020-01-25 12:12:20,360 : ConfigProcessor : Cache file not found: C:\Users\schol\AppData\Local\Temp\a6527a592b6034dbfea56fdf726c3822.mpf_cache
2020-01-25 12:12:20,360 : ConfigProcessor : Loading config from file E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml.
2020-01-25 12:12:20,365 : kivy : Base: Leaving application in progress...
2020-01-25 12:12:20,366 : kivy : Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x000001E28D79BFD0>>, priority=1, kwargs={}, key=UUID('fa1fd8dc-4ef8-4668-8d37-4f4da5e041aa'), condition=None, blocking_facility=None) for event init_phase_2
Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 197, in load
    config = self.process(f)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 222, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 144, in check_event
    self.current_event = self.state()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\parser.py", line 547, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 160, in check_token
    self.fetch_more_tokens()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 273, in fetch_more_tokens
    return self.fetch_value()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\scanner.py", line 626, in fetch_value
    self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 662, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 59, in _load_modes
    self.mc.modes[mode] = self._load_mode(mode)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 132, in _load_mode
    store_to_cache=self.mc.options['create_config_cache'], ignore_unknown_sections=True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 204, in load
    raise ValueError(msg)
ValueError: YAML error found in file E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml. Line 34, Position 35: mapping values are not allowed here
  in "E:\mpf\wows\wows\modes\container_lit\config\container_lit.yaml", line 34, column 35

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\kivy\clock.py", line 591, in tick
    self._process_events()
  File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\uix\display.py", line 205, in _displays_initialized
    self.mc.displays_initialized()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 336, in displays_initialized
    self._init()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 380, in _init
    self.events.process_event_queue()
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 743, in process_event_queue
    **event[3])
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 708, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "c:\users\schol\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 664, in _run_handlers
    raise Exception("Exception while processing {} for event {}".format(handler, event)) from e
Exception: Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x000001E28D79BFD0>>, priority=1, kwargs={}, key=UUID('fa1fd8dc-4ef8-4668-8d37-4f4da5e041aa'), condition=None, blocking_facility=None) for event init_phase_2
2020-01-25 12:12:20,371 : kivy : Stopping child threads... (1 remaining)
2020-01-25 12:12:21,375 : kivy : All child threads stopped.
